# Project information
site_name: 'Javascript'
site_description: 'Learn Javascript Online'
site_author: 'San Diego Code'
site_url: 'https://sdcoding.com/javascript'

pages:
- Home: index.md
- Introduction to JS: BeginnerJavascript.md
- Drawing App Project: HTML5DrawingApp.md

# Uncomment the below line to add lessons
#- Lesson 1: lesson1.md

#- PAGE NAME:  file.md

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/sandiegocode/javascript/'

# Copyright
copyright: Â© San Diego Code

# Documentation and theme
theme: 'material'

# Options
extra:
  palette:
    primary: 'red'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'sandiegocode'
  disqus: 'sandiegocode'

# Extensions
markdown_extensions:
  - admonition

#Compiler Code
#extra_css: [compiler.css]
#extra_javascript: [compiler.js]
